from sound_pool import SoundPool

from key_hold import key_hold
from savedata import savedata
from sound import sound

from pygame.locals import *
from vector import vector
from timer import timer
from network import network, network_event
from constants import DIRECTORY_APPDATA
from joystick import joystick_wrapper
buffers=[]
bufferpos=0
p=SoundPool()
pingpool=SoundPool()
invpos=0
inv={}
players=[]
map=[]
mapzones=[]
Left=0; Right=1; Backward=2; Forward=3; Up=4; Down=5
keylist=[]
crepeat=1
trackplayer=""
playlogo=1
firing=False
ka=key_hold(K_a,200,80)
kd=key_hold(K_d,200,80)
kw=key_hold(K_w,200,80)
ks=key_hold(K_s,200,80)
kpgdn=key_hold(K_PAGEDOWN,200,80)
kpgdn2=key_hold(K_PAGEDOWN,200,20)
kpgup=key_hold(K_PAGEUP,200,80)
kpgup2=key_hold(K_PAGEUP,200,20)
currentloc="Unknown area"
can_move=True
pinging=False
pingtimer=timer()
weaponauto=False
falltime=90
falling=False
falldistance=0
falltimer=timer()
movetime=0
jumptimer=timer()
jumping=False
jumptime=50
jumpup=0
jumplandz=0
airtime=100
firetime=180
firetimer=timer()
firetimer2=timer()
firetime2=180
weapons=[]
w=0
weapons2=[]
w2=0
creating=False
x=False
connected=False
ver="1.6.0"
name=""
password=""
facing=0
movetimer=timer()
walktime=250
me=vector();mr=vector();max=vector();camera=vector()
currentcameratile=""
mapname=""
n=network()
xtimer=timer()
sd=savedata(DIRECTORY_APPDATA+"/nbm-studios/zero_hour_assault/settings.dat")

distpool=SoundPool()
lastchar=""
s=sound()
doors=[]
dmoving=False
weapondrawtimer=timer()
playcanlogo=1
hrtf=1
getknife=False
tellweapon=""
loldietimer=timer()
mastervolume=1.10
mastervolume2=1.10

bufferlog=0
usemouse=1
FIRE_DEVICE_DEFAULT = 0
FIRE_DEVICE_MOUSE = 1
FIRE_DEVICE_KEYBOARD = 2
firedevice = FIRE_DEVICE_DEFAULT
mousex = 0
mousey = 0

fupdatetimer=timer()
playmusic=False
mus=None
ww=0
onlinemsg=1
killcounter=1
old_x=0; old_y=0; old_z=0; old_facing=0
usesub=1
awindow=1
muted=False
near=1
interrupt=1
focus0=""
focus1=""
focus2=""
focus3=""
focus4=""
focus5=""
focus6=""
focus7=""
focus8=""
focus9=""
parachute=False
charrepeat=1
watching=""
menumusvol=-30
lang="en"
lngdata=""
savemail=""
turningtimeelapsing=12
recording=False
vcdata=None
recording2=False
vcdata2=None

mapmusicoldversion=-25
mapmusic = sound()
musicplayinthemap=1
zombie=False
msounds=[]
web_message=""
motdhash=""
inthegame=False
scope=1
kleft=key_hold(K_LEFT,200,80)
kright=key_hold(K_RIGHT,200,80)
kup=key_hold(K_UP,200,80)
kdown=key_hold(K_DOWN,200,80)
tabtimer=timer()
shouldsetcaption=False
captiontoset=""
text_ctrl=None
label=None
window_handle=None
tempframe=None
keys_held=[]
shouldsetcaption2=False
samplerate=48000
bitrate=32000
listen=0
push=0
voicechatwho="sameteam"
volumeg=50
complexity=0
inputdevice=0
last_spoken_text=""
reverbs=[]
aim=0
eaxreverbs=[]
echos=[]
stopaim=0
stopaimtimer=timer()
ducking=False
maxwalktime=150
minwalktime=walktime
media_player=None
video_urls=[]
video_index=-1
paused=False
sticks=[]
stick=joystick_wrapper()
jcontrols={}
admin=False
builder=False
pyds=["zero_hour_assault.cp312-win_amd64.pyd","ticket_dialogs.cp312-win_amd64.pyd","joystick.cp312-win_amd64.pyd","internet.cp312-win_amd64.pyd","audio.cp312-win_amd64.pyd","buffer.cp312-win_amd64.pyd","cid.cp312-win_amd64.pyd","constants.cp312-win_amd64.pyd","dlg.cp312-win_amd64.pyd","dlgplay.cp312-win_amd64.pyd","door.cp312-win_amd64.pyd","downloader.cp312-win_amd64.pyd","events.cp312-win_amd64.pyd","file_directories.cp312-win_amd64.pyd","globals.cp312-win_amd64.pyd","inventory.cp312-win_amd64.pyd","key_hold.cp312-win_amd64.pyd","map.cp312-win_amd64.pyd","menu.cp312-win_amd64.pyd","menu_system.cp312-win_amd64.pyd","Miscellaneous.cp312-win_amd64.pyd","net.cp312-win_amd64.pyd","network.cp312-win_amd64.pyd","oal.cp312-win_amd64.pyd","pack_file.cp312-win_amd64.pyd","player.cp312-win_amd64.pyd","rotation.cp312-win_amd64.pyd","savedata.cp312-win_amd64.pyd","security.cp312-win_amd64.pyd","sound.cp312-win_amd64.pyd","sound_pool.cp312-win_amd64.pyd","sound_positioning.cp312-win_amd64.pyd","source.cp312-win_amd64.pyd","speech.cp312-win_amd64.pyd","timer.cp312-win_amd64.pyd","translation.cp312-win_amd64.pyd","updater.cp312-win_amd64.pyd","variable_management.cp312-win_amd64.pyd","vector.cp312-win_amd64.pyd","input.cp312-win_amd64.pyd","sign.cp312-win_amd64.pyd","moving_sound_client_handler.cp312-win_amd64.pyd"]
keytheme=1
voicechat=1
voicepresstimer=timer()
voicechat2=1
voicepresstimer2=timer()

templabel=None
favoriitem=""
favoriitem2=""

parachutesoundtimer=timer()
parachutesoundpositife=False
inve=False
matchteam=""
lastteam=""
signs=[]
trackx=-1
tracky=-1
trackz=-1
tracktimer=timer()
tracked=False
reloading=False
ingroup=False
incommunity=False

signbeepsound=1
invcategory="weapons"
invcategories={}
mapstairs=[]
buffersave=1
chat=True
voicechatmap=1
voicechatfriend=0
voicechatteam=0
mapignore_ambiences=[]
tutorial=0
playervolumes={}
rules3=0
transcache={}
speakdegree=1
speakfacing=1
fastwalk=1
lastdir=-3
stopwalktimer=timer()
buffersourcelang=""
buffertargetlang=""
sendsourcelang=""
sendtargetlang=""
should_translate=False
qturn=0
mapready=False
track2timer=timer()
ucd=0
voicechatgroup=0

canjump=1
sameteambots=1
sameteamplayers=1
differentteambots=1
differentteamplayers=1
samegroupplayers=1
differentgroupplayers=1
charvoice=1
rainsnd=sound()
rainsound=""
sound=1
cannotexit=False
cannotexittimer=timer()
cannotexittime=0
reply=""
candraw=True
privacy=0
near2=False
died=False
canduck=1
maxaim=0
sitting=False
standing=False
standingtimer=timer()
invmenu=False
oldw=-1
weaponauto2=False
exiting=False
should_watch=False
langkey="krjlkjelkryjelwkjyrkojyoeıjyroeyjurıoeyuorıuowıyuoıyreuwhoıroehjorehjlkrjehkljelkhjrlkhjdbgggggkhymtjgdmhtrmhtrmhtrmhtrmhtrorssssssssssssssssssssspıu0609r7860959087609870969085459074867904890583753874985365643987569384753984376598749087590483uopıthrjhpkjtgşlksdlsşfkdfşlsjdfşlsdkfasfdsfşasfasdfasdasdsafmgkjasoaryoıjuf"
cheatengine=False
cheattimer=timer()
drawing=False
drawtime=0
drawtimer=timer()
nomudtileslist=[]
rain=False
rainvolume=0
nomudtiles=[]
soundcard=None
sonar=0
sonartimer=timer()
rainfinish=False
push2=0
rainslot=None
raineffect=None
tile_cache={}
wallhittimer=timer()
playeds=set()
holding_wall=False
steam=0
rainfadein=False
target_rain_volume=0
yavaslat=0
itembeep=1
autotrack=0
inbike=False
kp7=key_hold(K_KP7,200,20)
kp9=key_hold(K_KP9,200,20)
cache=1
aim_mode=1
font=None
title_font=None
tile_count=0
tiletimer=timer()